local CN = {
    ["Quality1"] = "常见",
    ["Quality2"] = "罕见",
    ["Quality3"] = "稀有",
    ["Quality4"] = "珍稀",
    ["Quality5"] = "传说",
    ["FishGrade0"] = "稚鱼",
    ["FishGrade1"] = "幼鱼",
    ["FishGrade2"] = "成鱼",
    ["AquariumSelectCurrent"] = "当  前",
    ["UpgradeButtonBatch"] = "X{0}",
    ["LevelUpFull"] = "满  级",
    ["ShowFish"] = "放  入",
    ["UnlockRightNow"] = "立即解锁",
    ["GetDecoration"] = "获得",
    ["TimeUnlockDesc"] = "钓鱼获得:{0}分钟内",
    ["WaitUnlock"] = "等待解锁",
    ["UnitSeconds"] = "/秒",
    ["Developping"] = "功能正在开发",
    ["Level"] = "{0}级",
    ["Unlock"] = "解  锁",
    ["CannotUnlock"] = "未发现任何踪迹",
    ["PayToGain"] = "获得",
    ["ADReward"] = "{0}  倍",
    ["NoADThanks"] = "不用，谢谢",
    ["Growth"] = "成  长",
    ["TitleUnlockDecoration"] = "获得装饰物",
    ["TitleUnlockFish"] = "放入鱼",
    ["Cooooool"] = "哦  耶!",
    ["Good"] = "[color=#ffffff,#e6c251]真棒![/color]",
    ["Bad"] = "[color=#ffffff,#e6c251]抛竿角度不佳[/color]",
    ["GameQuality1"] = "极致",
    ["GameQuality2"] = "高清",
    ["GameQuality3"] = "省电",
    ["Recommend"] = "推荐",
    ["Account"] = "帐号：",
    ["Sure"] = "确定",
    ["Cancel"] = "取消",
    ["SetHighGraphicTip"] = "调整到推荐以上可能导致手机卡顿。",
    ["SetGreenGraphicTip"] = "切换为省电画质，可以降低性能消耗，提高游戏续航",
    ["OfflineTime"] = "离线时间",
    ["OfflineReward"] = "欢迎回来",
    ["DoubleMoneyTime"] = "收益翻倍时间",
    ["DoubleMoneyDesc1"] = "投放广告，累计最长获得",
    ["DoubleMoneyDesc2"] = "{0}分钟的收益翻倍时间",
    ["DoDoubleMoney"] = "收益翻倍",
    ["DoAdvertise"] = "投放广告",
    ["LunchTime"] = "吃饭时间",
    ["LunchTimeDesc1"] = "吃饭时段7~10点、11~14点、17~24点",
    ["LunchTimeDesc2"] = "立即获得{0}分钟的收益",
    ["DoDinner"] = "开  饭",
    ["EnterSea"] = "前往海域",
    ["DoTrain"] = "进  修",
    ["FreeTrain"] = "免费进修",
    ["OneKeyTrain"] = "一键进修",
    ["GetReward"] = "领  取",
    ["InWaterBox"] = "漂流宝箱",
    ["ShipTreasure"] = "沉船探宝",
    ["ShipTreasureTip"] = "探沉船，获金币",
    ["ChangeSea"] = "切换海域",
    ["ReturnSea"] = "返回海域",
    ["ShowFishReady"] = "已达成所有条件",
    ["NotEnoughDiamond"] = "钻石不足",
    ["Achievement"] = "成就",
    ["TotalProgress"] = "总进度",
    ["AchieveTitle"] = "成就称号",
    ["AchieveTitleCondition"] = "累计完成{0}个成就",
    ["DefaultAchieveTitle"] = "这是你的默认称号",
    ["Current"] = "当  前",
    ["AchieveTotalPrize"] = "成就累计奖励",
    ["AquariumSelectTitle"] = " 切换观赏馆",
    ["GoTo"] = " 前往",
    ["PlayerInformation"] = " 个人信息",
    ["GrabNow"] = " 立即获得",
    ["DoubleTimeLimited"] = " 不足9小时可继续投放",
    ["GetReward2"] = "领取",
    ["GetReward3"] = "领取%s",
    ["Look"] = "查看",
    ["Task"] = "任务",
    ["Reward"] = "奖励",
    ["Tips"] = "提示",
    ["FishShipHasReward"] = "船已返航，点击领取奖励",
    ["ComeBackImmediately"] = "立即返航",
    ["ShipFish"] = "远洋捕捞",
    ["Free"] = "免费",
    ["FuncUnlockIncome"] = "收益 %s/秒",
    ["LoadAdFail"] = "广告加载失败",
    ["Challenge"] = "挑  战",
    ["GiveUp"] = "放 弃",
    ["GiveUpTips"] = "是否放弃钓起这条鱼?\n如果操作对您来说有点难度,可以考虑观看一段视频后立即解锁这条鱼。",
    ["DoubleTitleRewardTips"] = "是否播放视频支持一下我们\n并且{0}倍领取奖励？",
    ["Dialog_5_1"] = "远离了喧嚣，你回到了儿时的海边小城。熟悉的海风，治愈了你疲倦的心情…",
    ["Dialog_10_1"] = "喂！是你吗，我终于等到你了！不记得我了吗？小时候我们每天都会到海边来玩啊，一起等着大人们出海钓鱼回来，给我们看那些稀奇古怪的鱼。",
    ["Dialog_10_2"] = "你的爷爷，也就是我们钓鱼协会前任会长啦，他给你留了一座水族[color=#ffff00]观赏馆[/color]。可惜这些年没人管理逐渐荒废了。",
    ["Dialog_10_3"] = "现在你回来啦，观赏馆终于又有希望了！你的钓鱼技术一定像爷爷那么棒吧！",
    ["Dialog_10_4"] = "我们一起周游世界，肯定能钓到各种珍稀的鱼，再带回来放入观赏馆，游客慕名前来，我们也能赚到一大笔钱。",
    ["Dialog_10_5"] = "赶快出发吧，美丽的[color=#ffff00]加勒比[/color]，古老的神秘之海！",
    ["Dialog_20_1"] = "什么？你根本不会钓鱼？挑战全球海域可是我们小时候的梦想！好吧，就让我来教你吧。你是老会长的后代，相信你肯定有钓鱼的天赋。",
    ["Dialog_20_2"] = "[color=#ffff00]快！握住你的鱼竿吧[/color]，尽快征服加勒比，下一站夏威夷还在等着我们呢！",
    ["Dialog_30_1"] = "好机会！\n[color=#ffff00]往提示方向滑动手指[/color]，\n大量削弱鱼的体力！",
    ["Dialog_40_1"] = "真棒！作为新手能掌握得这么快，第一次就能钓到了神仙鱼，果然是天赋异禀啊。",
    ["Dialog_40_2"] = "[color=#ffff00]喂养升级[/color]已经钓到的鱼，可以为我们带来[color=#ffff00]持续的收益[/color]。",
    ["Dialog_45_1"] = "钓鱼协会对于你的进步表示肯定，他们还设置了一系列的考核任务，期待你早日成为像爷爷那样的[color=#ffff00]钓鱼大亨[/color]。",
    ["Dialog_45_2"] = "现在，领取你的第一笔[color=#ffff00]任务奖励[/color]吧。",
    ["Dialog_47_1"] = "我们的[color=#ffff00]观赏馆[/color]准备开放了，将钓到的鱼[color=#ffff00]放入[/color]进去吧。",
    ["Dialog_47_2"] = "络绎不绝的游客会带来持续收益，为我们的钓鱼事业提供资金支持。以后我们会开设更多不同主题风格的观赏馆。",
    ["Dialog_49_1"] = "点这儿，可以[color=#ffff00]调高升级倍数[/color]，升级更轻松哦！",
    ["Dialog_51_1"] = "钓鱼可不仅仅只是实战，有时候，恰当的理论知识能让你事半功倍。快去[color=#ffff00]进修[/color]吧，让其他人为你的技术而惊叹吧。",
    ["Dialog_52_1"] = "[color=#ffff00]成就[/color]功能解锁了，这代表着你获得的荣誉。满足不同的条件可以解锁各式各样的成就称号。",
    ["Dialog_60_1"] = "加勒比海域已经没有更多的鱼可以供你挑战了。让我们探索新的海域吧——下一站，[color=#ffff00]夏威夷[/color]！",
    ["Dialog_60_2"] = "喜欢小丑鱼吗？我们即刻出发去夏威夷吧！",
    ["Dialog_70_1"] = "我们已经在夏威夷海域待了一段时间了，我们建立一个夏威夷主题的[color=#ffff00]新观赏馆[/color]吧，游客们一定会喜欢的。",
    ["Dialog_70_2"] = "领略夏威夷的“热带风情”吧！",
    ["Dialog_55_1"] = "太棒了！沉船宝藏馆所有装饰物都齐全了！前往夏威夷之前，[color=#ffff00]对装饰物再进行几次升级[/color]吧。",
    ["KillTheHunter"] = "击败捕食者!",
    ["ClickToClose"] = "点击关闭界面",
    ["Break"] = "开始突破",
    ["AdBreak"] = "立即突破",
    ["OtherBreaking"] = "其他突破进行中",
    ["DoBreak"] = "完成突破",
    ["BreakAfter"] = "%s后完成",
    ["IncomeAdd"] = "收益+%s/s",
    ["ImproveBreakNum"] = "进修累计突破 [color=#FFDD21]{0}[/color] 次",
    ["ShipFreeCd"] = "免费探宝冷却中",
    ["UnlockRequire"] = "解锁条件:",
    ["PlayerFish"] = "按住钓鱼",
    ["GoToShipTreasure"]= "金币不足，可去沉船探宝",
    ["AdBreakTips"] = "是否观看一段广告以立即突破？",
    ["GetRewardNow"] = "直接领取",
    ["ADLoadError"] = "广告加载失败, 请稍后重试",
    ["ADPlayError"] = "广告播放失败, 请稍后重试",
    ["ADLoading"] = "广告加载中, 请稍后",
    ["Maintab0"] = "观赏馆",
    ["Maintab1"] = "进修",
    ["Maintab2"] = "钓鱼",
    ["Maintab3"] = "游艇",
    ["Maintab4"] = "成就",
    ["Revenue"] = "收益",
    ["FunctionLockTips"] = "升级鱼和装饰物，可提升收益值",
    ["NewDiscovery"] = "新发现",
    ["GrownUp"] = "成长啦",
    ["CostTips"] = "消耗：",
}

return CN
