local m = {
    ["Quality1"] = "Common",
    ["Quality2"] = "Uncommon",
    ["Quality3"] = "Rare",
    ["Quality4"] = "Epic",
    ["Quality5"] = "Legendary",
    ["FishGrade0"] = "Juvenile Fish",
    ["FishGrade1"] = "Young Fish",
    ["FishGrade2"] = "Adult Fish",
    ["AquariumSelectCurrent"] = "Current",
    ["UpgradeButtonBatch"] = "X{0}",
    ["LevelUpFull"] = "Max level",
    ["ShowFish"] = "Put In",
    ["UnlockRightNow"] = "Unlock now",
    ["GetDecoration"] = "Get",
    ["TimeUnlockDesc"] = "Fishing: within {0} minutes",
    ["WaitUnlock"] = "Locked",
    ["UnitSeconds"] = "/s",
    ["Developping"] = "Coming soon",
    ["Level"] = "Level {0}",
    ["Unlock"] = "Unlock",
    ["CannotUnlock"] = "No trace found",
    ["PayToGain"] = "Get",
    ["ADReward"] = "{0} times",
    ["NoADThanks"] = "No, thanks",
    ["Growth"] = "Grow",
    ["TitleUnlockDecoration"] = "Get decorations",
    ["TitleUnlockFish"] = "Put in the fish",
    ["Cooooool"] = "Oh yeah!",
    ["Good"] = "[color=#ffffff,#e6c251]Awesome![/color]",
    ["Bad"] = "[color=#ffffff,#e6c251]Bad angle[/color]",
    ["GameQuality1"] = "High",
    ["GameQuality2"] = "Medium",
    ["GameQuality3"] = "Low",
    ["Recommend"] = "Recommended",
    ["Account"] = "Account:",
    ["Sure"] = "Confirm",
    ["Cancel"] = "Cancel",
    ["SetHighGraphicTip"] = "Adjusting above the recommended settings may cause phone lag.",
    ["SetGreenGraphicTip"] = "Switching to low quality can reduce performance consumption and improve battery life",
    ["OfflineTime"] = "Offline Time",
    ["OfflineReward"] = "Welcome Back",
    ["DoubleMoneyTime"] = "Revenue doubling time",
    ["DoubleMoneyDesc1"] = "Advertise and get the longest accumulative total",
    ["DoubleMoneyDesc2"] = "Revenue doubles for{0}m",
    ["DoDoubleMoney"] = "Watch Ad",
    ["DoAdvertise"] = "Advertise",
    ["LunchTime"] = "Meal time",
    ["LunchTimeDesc1"] = "Meal time 7-10:00, 11-14:00, 17-24:00",
    ["LunchTimeDesc2"] = "Get instant revenue for {0}m",
    ["DoDinner"] = "Meal Served",
    ["EnterSea"] = "Go to the seas",
    ["DoTrain"] = "Train",
    ["FreeTrain"] = "Free Training",
    ["OneKeyTrain"] = "Train All",
    ["GetReward"] = "Claim",
    ["InWaterBox"] = "Drifting Chest",
    ["ShipTreasure"] = "Shipwreck treasure hunt",
    ["ShipTreasureTip"] = "Explore the shipwreck to get coins",
    ["ChangeSea"] = "Switch seas",
    ["ReturnSea"] = "Return to seas",
    ["ShowFishReady"] = "All requirements met",
    ["NotEnoughDiamond"] = "Not enough diamonds",
    ["Achievement"] = "Achievement",
    ["TotalProgress"] = "Total progress",
    ["AchieveTitle"] = "Achievement title",
    ["AchieveTitleCondition"] = "{0} Achievements accomplished",
    ["DefaultAchieveTitle"] = "This is your default title",
    ["Current"] = "Current",
    ["AchieveTotalPrize"] = "Achievement cumulative reward",
    ["AquariumSelectTitle"] = "  Switch",
    ["GoTo"] = "  Go To",
    ["PlayerInformation"] = "  Profile",
    ["GrabNow"] = "  Get immediately",
    ["DoubleTimeLimited"] = "  Continue to serve when less than 9 hours",
    ["GetReward2"] = "Claim",
    ["GetReward3"] = "Claim %s",
    ["Look"] = "Check",
    ["Task"] = "Task",
    ["Reward"] = "Reward",
    ["Tips"] = "Tip",
    ["FishShipHasReward"] = "Click to claim the reward",
    ["ComeBackImmediately"] = "Return Immediately",
    ["ShipFish"] = "Pelagic Fishing",
    ["Free"] = "Free",
    ["FuncUnlockIncome"] = "Revenue %s/sec",
    ["LoadAdFail"] = "Ad failed to load",
    ["Challenge"] = "Challenge",
    ["GiveUp"] = "Give Up",
    ["GiveUpTips"] = "Give up on catching this fish?\nIf it's bit challenging for you, you may watch a video to unlock the fish right away.",
    ["DoubleTitleRewardTips"] = "Would you like to play a video to support us\nand claim {0} times the reward?",
    ["Dialog_5_1"] = "Want to get away from the hustle and bustle, you return to your childhood seaside town. The familiar sea breeze makes you forget your tiredness...",
    ["Dialog_10_1"] = "Hey! It's you! Don't remember me? When we were young, we would go to the beach every day, waiting for the adults to come back from fishing and show us those strange fish.",
    ["Dialog_10_2"] = "Your grandfather, the former president of our Fishing Association, left you an [color=#ffff00]gallery[/color]. It's a pity that no one has taken care of it over the years and it has gradually become abandoned.",
    ["Dialog_10_3"] = "Now you are back, the gallery finally has hope again! Your fishing skills must be as good as grandpa's!",
    ["Dialog_10_4"] = "We can travel around the world to catch all kinds of rare fish, and bring them back to the gallery.Crowded tourists will bring us big fortune!",
    ["Dialog_10_5"] = "Let's go!the beautiful [color=#ffff00]Caribbean[/color], the ancient sea of mystery!",
    ["Dialog_20_1"] = "What? You can't fish? It was our dream to challenge the global seas! Well, let me teach you. I bet you have the fishing talent inherited.",
    ["Dialog_20_2"] = "[color=#ffff00]Quick! Grab your rod[/color] and conquer the Caribbean, Hawaii still awaits for us!",
    ["Dialog_30_1"] = "Good chance! \n[color=#ffff00]Slide your finger in the direction of the prompt[/color],\nWeaken the fish's energy a lot!",
    ["Dialog_40_1"] = "Awesome!Angelfish for the first time,you are real talented as a novice.",
    ["Dialog_40_2"] = "[color=#ffff00]Feeding and upgrading[/color] the fish that we have caught will bring[color=#ffff00]continuous revenue[/color].",
    ["Dialog_45_1"] = "The Fishing Association affirmed your progress and have set up a series of tasks. They expect you to become a [color=#ffff00]fishing tycoon[/color] like your grandpa.",
    ["Dialog_45_2"] = "Now, claim your first [color=#ffff00]task reward[/color].",
    ["Dialog_47_1"] = "Our [color=#ffff00]gallery[/color] is ready to open, [color=#ffff00]put[/color] the fish in it.",
    ["Dialog_47_2"] = "Tourists bring in continual revenue that provides financial support for our fishing business. We will open more galleries with different themes in the future.",
    ["Dialog_49_1"] = "Click here to [color=#ffff00]increase the upgrade multiplier[/color] to upgrade faster!",
    ["Dialog_51_1"] = "Fishing is more than just experience. Sometimes, the right theoretical knowledge can make you more productive with less effort. Go to [color=#ffff00]training[/color], and let others be amazed by your skills.",
    ["Dialog_52_1"] = "[color=#ffff00]Achievement[/color] has been unlocked, which represents the honor you have received. Meet different requirements to unlock a variety of achievement titles.",
    ["Dialog_60_1"] = "There are no more fish in the Caribbean for you to challenge. Let's explore new seas - next stop, [color=#ffff00]Hawaii[/color]!",
    ["Dialog_60_2"] = "Like clownfish? Let's go to Hawaii now!",
    ["Dialog_70_1"] = "We have been in Hawaiian waters for a while, let's build a Hawaiian-themed [color=#ffff00]new gallery[/color], tourists will love it.",
    ["Dialog_70_2"] = "Enjoy the \"tropical style\" of Hawaii!",
    ["Dialog_55_1"] = "Perfect! we've got all decorations! Before heading to Hawaii, [color=#ffff00]Upgrade the decorations a few times[/color].",
    ["KillTheHunter"] = "Defeat the Predator!",
    ["ClickToClose"] = "Click to close",
    ["Break"] = "Start to break",
    ["AdBreak"] = "Break now",
    ["OtherBreaking"] = "Waiting for another",
    ["DoBreak"] = "Breakthrough Completed",
    ["BreakAfter"] = "Complete in %s",
    ["IncomeAdd"] = "Revenue+%s/s",
    ["ImproveBreakNum"] = "Train [color=#FFDD21]{0}[/color] times in total",
    ["ShipFreeCd"] = "Free treasure hunt is on Cd",
    ["UnlockRequire"] = "Unlock requirements:",
    ["PlayerFish"] = "Hold",
    ["GoToShipTreasure"] = "Go Shipwreck treasure hunt to get coins",
    ["AdBreakTips"] = "Watching an ad to start break immediately?",
    ["GetRewardNow"] = "Claim immediately",
    ["ADLoadError"] = "Ad failed to load, please try again later",
    ["ADPlayError"] = "The ad failed to play, please try again later",
    ["ADLoading"] = "Ad loading, please wait",
    ["Maintab0"] = "Gallery",
    ["Maintab1"] = "Train",
    ["Maintab2"] = "Fishing",
    ["Maintab3"] = "Yacht",
    ["Maintab4"] = "Achievement",
    ["Revenue"] = "Revenue",
    ["FunctionLockTips"] = "Upgrade fish and decorations to increase the revenue",
    ["NewDiscovery"] = "New Discovery",
    ["GrownUp"] = "Grown Up",
    ["CostTips"] = "Cost: ",
}

return m