---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kimi.
--- DateTime: 2019/8/20 17:35
---

local CompassUtils = {}


--初始化指南针组件
function CompassUtils.Init()
    Input.compass.enabled = true;
    Input.location:Start();
end

--获取指南针方向
function CompassUtils.GetCompassRotation()
    return Input.compass.trueHeading
end

return CompassUtils