---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kimi.
--- DateTime: 2019/8/20 15:58
---

local GyroUtils = {}
local mGyro = nil


--初始化陀螺仪组件
function GyroUtils.Init()
    mGyro = Input.gyro
    mGyro.enabled = true
    mGyro.updateInterval = 0.1
end

--获取当前速度
function GyroUtils.GetSpeed(curSpeed, maxSpeed)
    
    curSpeed = curSpeed + mGyro.rotationRateUnbiased.y
    curSpeed = curSpeed - curSpeed/20; --减速系数
    
    if curSpeed >= maxSpeed then
        return maxSpeed
    end
    if curSpeed <= -maxSpeed then
        return -maxSpeed
    end
    return curSpeed
end

--获取当前速率
function GyroUtils.GetRotationRateUnbiasedY()
    if CS.UnityEngine.Screen.orientation == CS.UnityEngine.ScreenOrientation.LandscapeRight then
        return mGyro.attitude.z + 1
    end
    return mGyro.attitude.z - 1
end

return GyroUtils