-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	AudioConfig = {
		{ ID = 1, Name = "BGM_Caribbean01", Loops = true, Path = "Audio/BGM_Caribbean01.mp3", Extent = "mp3", Desc = "加勒比钓鱼场景音乐" 	},
		{ ID = 2, Name = "BGM_Hawaii01", Loops = true, Path = "Audio/BGM_Hawaii01.mp3", Extent = "mp3", Desc = "夏威夷钓鱼场景音乐" 	},
		{ ID = 3, Name = "BGM_Alaska01", Loops = true, Path = "Audio/BGM_Alaska01.mp3", Extent = "mp3", Desc = "阿拉斯加钓鱼场景音乐" 	},
		{ ID = 40, Name = "BGM_Battle01", Loops = true, Path = "Audio/BGM_Battle01.mp3", Extent = "mp3", Desc = "进入手动钓鱼场景后停止场景音乐，在鱼上钩后播战斗音乐" 	},
		{ ID = 50, Name = "AMB_SeaWaves01", Loops = true, Path = "Audio/AMB_SeaWaves01.mp3", Extent = "mp3", Desc = "海浪环境音效" 	},
		{ ID = 55, Name = "AMB_Aquarium", Loops = true, Path = "Audio/AMB_Aquarium.mp3", Extent = "mp3", Desc = "处于观赏馆场景时播的环境音效" 	},
		{ ID = 60, Name = "AMB_Thunder01", Loops = false, Path = "Audio/AMB_Thunder01.mp3", Extent = "mp3", Desc = "雷声1" 	},
		{ ID = 61, Name = "AMB_Thunder02", Loops = false, Path = "Audio/AMB_Thunder02.mp3", Extent = "mp3", Desc = "雷声2" 	},
		{ ID = 100, Name = "Button_Click01", Loops = false, Path = "Audio/Button_Click01.mp3", Extent = "mp3", Desc = "通用缺省点击音效" 	},
		{ ID = 101, Name = "Button_Click02", Loops = false, Path = "Audio/Button_Click02.mp3", Extent = "mp3", Desc = "另一种用于填补表现力的通用点击音效" 	},
		{ ID = 102, Name = "Button_ClickCoin01", Loops = false, Path = "Audio/Button_ClickCoin01.mp3", Extent = "mp3", Desc = "通用点击场景增长金币音效" 	},
		{ ID = 103, Name = "Button_Draw", Loops = false, Path = "Audio/Button_Draw.mp3", Extent = "mp3", Desc = "展开按钮" 	},
		{ ID = 104, Name = "Button_PopUp", Loops = false, Path = "Audio/Button_PopUp.mp3", Extent = "mp3", Desc = "弹窗动效声音" 	},
		{ ID = 105, Name = "Button_AwardCoin", Loops = false, Path = "Audio/Button_AwardCoin.mp3", Extent = "mp3", Desc = "通用获得金币动画的音效" 	},
		{ ID = 106, Name = "Button_AwardCoinBanner", Loops = false, Path = "Audio/Button_AwardCoinBanner.mp3", Extent = "mp3", Desc = "通用金币货币栏动画的音效" 	},
		{ ID = 107, Name = "Button_AwardDiamond", Loops = false, Path = "Audio/Button_AwardDiamond.mp3", Extent = "mp3", Desc = "通用获得钻石动画的音效" 	},
		{ ID = 108, Name = "Button_AwardDiamondBanner", Loops = false, Path = "Audio/Button_AwardDiamondBanner.mp3", Extent = "mp3", Desc = "通用钻石货币栏动画的音效" 	},
		{ ID = 109, Name = "Button_Grid", Loops = false, Path = "Audio/Button_Grid.mp3", Extent = "mp3", Desc = "进度格增长音效" 	},
		{ ID = 1000, Name = "Button_Unlock", Loops = false, Path = "Audio/Button_Unlock.mp3", Extent = "mp3", Desc = "点击【解锁】按钮音效" 	},
		{ ID = 1001, Name = "Button_Level", Loops = false, Path = "Audio/Button_Level.mp3", Extent = "mp3", Desc = "点击【升级】按钮音效" 	},
		{ ID = 1002, Name = "Button_Grow", Loops = false, Path = "Audio/Button_Grow.mp3", Extent = "mp3", Desc = "点击【成长】按钮音效" 	},
		{ ID = 1003, Name = "Button_PutIn", Loops = false, Path = "Audio/Button_PutIn.mp3", Extent = "mp3", Desc = "点击【放入】按钮音效" 	},
		{ ID = 1004, Name = "Button_Bubble", Loops = false, Path = "Audio/Button_Bubble.mp3", Extent = "mp3", Desc = "点击鱼类互动音效" 	},
		{ ID = 1005, Name = "Button_Evolution", Loops = false, Path = "Audio/Button_Evolution.mp3", Extent = "mp3", Desc = "鱼类/装饰物进化音效" 	},
		{ ID = 1006, Name = "Button_CutToBubble", Loops = false, Path = "Audio/Button_CutToBubble.mp3", Extent = "mp3", Desc = "全屏气泡转场音效" 	},
		{ ID = 1007, Name = "Button_BoxClick", Loops = false, Path = "Audio/Button_BoxClick.mp3", Extent = "mp3", Desc = "点开宝箱弹窗时的音效" 	},
		{ ID = 1008, Name = "Button_BoxOpen", Loops = false, Path = "Audio/Button_BoxOpen.mp3", Extent = "mp3", Desc = "宝箱打开时的音效" 	},
		{ ID = 1009, Name = "Button_CutToSea", Loops = false, Path = "Audio/Button_CutToSea.mp3", Extent = "mp3", Desc = "切换海域" 	},
		{ ID = 1010, Name = "Button_CutToAquarium", Loops = false, Path = "Audio/Button_CutToAquarium.mp3", Extent = "mp3", Desc = "切换观赏馆" 	},
		{ ID = 3000, Name = "Sfx_CastButton", Loops = false, Path = "Audio/Sfx_CastButton.mp3", Extent = "mp3", Desc = "确定抛竿" 	},
		{ ID = 3001, Name = "Sfx_DecideWindow", Loops = false, Path = "Audio/Sfx_DecideWindow.mp3", Extent = "mp3", Desc = "判定弹窗" 	},
		{ ID = 3002, Name = "Sfx_CastWinder", Loops = false, Path = "Audio/Sfx_CastWinder.mp3", Extent = "mp3", Desc = "卷线器放线音效" 	},
		{ ID = 3003, Name = "Sfx_FallIntoWater", Loops = false, Path = "Audio/Sfx_FallIntoWater.mp3", Extent = "mp3", Desc = "鱼钩落水" 	},
		{ ID = 3004, Name = "Sfx_GetHooked", Loops = false, Path = "Audio/Sfx_GetHooked.mp3", Extent = "mp3", Desc = "鱼儿上钩事件音效" 	},
		{ ID = 3005, Name = "Sfx_Winder01", Loops = true, Path = "Audio/Sfx_Winder01.mp3", Extent = "mp3", Desc = "按下转动卷线器01" 	},
		{ ID = 3006, Name = "Sfx_Winder02", Loops = true, Path = "Audio/Sfx_Winder02.mp3", Extent = "mp3", Desc = "按下转动卷线器02" 	},
		{ ID = 3007, Name = "Sfx_LinePull01", Loops = true, Path = "Audio/Sfx_LinePull01.mp3", Extent = "mp3", Desc = "鱼竿鱼线被拉紧的音效（1档）" 	},
		{ ID = 3008, Name = "Sfx_LinePull02", Loops = true, Path = "Audio/Sfx_LinePull02.mp3", Extent = "mp3", Desc = "鱼竿鱼线被拉紧的音效（2档）" 	},
		{ ID = 3009, Name = "Sfx_Slide", Loops = false, Path = "Audio/Sfx_Slide.mp3", Extent = "mp3", Desc = "滑动操作触发成功的音效" 	},
		{ ID = 3010, Name = "Sfx_SlideHit", Loops = false, Path = "Audio/Sfx_SlideHit.mp3", Extent = "mp3", Desc = "滑动操作暴击掉血音效" 	},
		{ ID = 3011, Name = "Sfx_FishJump", Loops = false, Path = "Audio/Sfx_FishJump.mp3", Extent = "mp3", Desc = "鱼儿跃出水面音效" 	},
		{ ID = 3012, Name = "Sfx_FishFallIntoWater", Loops = false, Path = "Audio/Sfx_FishFallIntoWater.mp3", Extent = "mp3", Desc = "鱼儿落入水面音效" 	},
		{ ID = 3013, Name = "Sfx_FishSurfing", Loops = false, Path = "Audio/Sfx_FishSurfing.mp3", Extent = "mp3", Desc = "鱼儿被大力拽过来的音效" 	},
		{ ID = 3014, Name = "Sfx_FishPullUp", Loops = false, Path = "Audio/Sfx_FishPullUp.mp3", Extent = "mp3", Desc = "鱼儿出水音效" 	},
		{ ID = 3015, Name = "Sfx_FishStruggle", Loops = false, Path = "Audio/Sfx_FishStruggle.mp3", Extent = "mp3", Desc = "鱼儿挣扎音效（配合动作）" 	}
	}

}


-- ID
tab.AudioConfigByID = {}
for _, rec in pairs(tab.AudioConfig) do
	tab.AudioConfigByID[rec.ID] = rec
end

tab.Enum = {
}

return tab