-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	ConstValues = {
		{ Key = "InitCoinNum", Value = "10000", ValueType = "int64" 	},
		{ Key = "InitDiamondNum", Value = "0", ValueType = "int64" 	},
		{ Key = "BaseIncome", Value = "60", ValueType = "int64" 	}
	}

}


-- Key
tab.ConstValuesByKey = {}
for _, rec in pairs(tab.ConstValues) do
	tab.ConstValuesByKey[rec.Key] = rec
end

tab.Enum = {
}

return tab