-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	Functions = {
		{ ID = 1, Title = "观赏馆", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 5000, MainTask = 0 	},
		{ ID = 2, Title = "进修", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 2000000, MainTask = 0 	},
		{ ID = 3, Title = "钓鱼", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 0 	},
		{ ID = 4, Title = "游艇", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 8E+16, MainTask = 0 	},
		{ ID = 5, Title = "成就", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 50000000, MainTask = 0 	},
		{ ID = 6, Title = "沉船探宝", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 6 	},
		{ ID = 7, Title = "双倍增益", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 5 	},
		{ ID = 8, Title = "漂流宝箱", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 9 	},
		{ ID = 9, Title = "远洋捕捞", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 12 	},
		{ ID = 10, Title = "吃饭时间", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 11 	}
	}

}


-- ID
tab.FunctionsByID = {}
for _, rec in pairs(tab.Functions) do
	tab.FunctionsByID[rec.ID] = rec
end

tab.Enum = {
}

return tab