-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	MainTask = {
		{ ID = 1, Name = "挑战【石斑鱼】", Desc = "据经验丰富的渔夫所言，此鱼常[color=#ffff00]出没于加勒比海[/color]与佛罗里达南部。", TaskId = 1, Prev = 0, RewardType = 1, Reward = 230000 	},
		{ ID = 2, Name = "将【石斑鱼】升到10级", Desc = "[color=#ffff00]点击按钮[/color]就可以轻松提升等级，增加我们的金币收益。", TaskId = 2, Prev = 1, RewardType = 1, Reward = 690000 	},
		{ ID = 3, Name = "挑战第3条鱼", Desc = "据说最近加勒比海里有[color=#ffff00]大白鲨[/color]出现，出海钓鱼可得注意安全。快去挑战更多的鱼吧！", TaskId = 3, Prev = 2, RewardType = 2, Reward = 50 	},
		{ ID = 4, Name = "解锁【观赏馆】", Desc = "建设观赏馆，把钓到鱼统统放入观赏馆吧。", TaskId = 4, Prev = 3, RewardType = 2, Reward = 20 	},
		{ ID = 5, Name = "解锁【观赏馆-加勒比樱蕾海葵】", Desc = "[color=#ffff00]解锁观赏馆里的【加勒比樱蕾海葵】[/color]之后，[color=#ffff00]就可以将钓到的神仙鱼放进观赏馆[/color]了呢！", TaskId = 5, Prev = 4, RewardType = 2, Reward = 20 	},
		{ ID = 6, Name = "解锁【观赏馆-加勒比千佛手】", Desc = "[color=#ffff00]解锁观赏馆里的【加勒比千佛手】[/color]，[color=#ffff00]就能把石斑鱼放进观赏馆[/color]啦！如果金币不足，建议进行【沉船探宝】", TaskId = 6, Prev = 5, RewardType = 2, Reward = 20 	},
		{ ID = 7, Name = "解锁【加勒比奇型海石】", Desc = "我们钓到了大白鲨，期待把它放入观赏馆吗？我们[color=#ffff00]需要升级和解锁更多观赏馆的【装饰物】[/color]。", TaskId = 7, Prev = 6, RewardType = 2, Reward = 20 	},
		{ ID = 8, Name = "解锁【观赏馆-加勒比武装海葵】", Desc = "[color=#ffff00]观赏馆解锁足够多的装饰物[/color]，放入大白鲨(稚鱼)。如果金币不足，建议进行【沉船探宝】", TaskId = 8, Prev = 7, RewardType = 2, Reward = 60 	},
		{ ID = 9, Name = "前往【进修】", Desc = "多多钓鱼，多多升级鱼和装饰物，[color=#ffff00]收益提升到【2M/秒】[/color]之后，就可以前往进修啦！", TaskId = 9, Prev = 8, RewardType = 2, Reward = 20 	},
		{ ID = 10, Name = "【钓鱼】累计挑战5条鱼", Desc = "钓到的鱼全部放入观赏馆啦，我们[color=#ffff00]回到加勒比海域继续【钓鱼】[/color]吧！", TaskId = 10, Prev = 9, RewardType = 2, Reward = 20 	},
		{ ID = 11, Name = "寻找【紫色琥珀鱼】", Desc = "[color=#ffff00]继续升级和挑战更多鱼[/color]，直至发现珍稀的【紫色琥珀鱼】。", TaskId = 11, Prev = 10, RewardType = 2, Reward = 20 	},
		{ ID = 12, Name = "【紫色琥珀鱼】升到120级", Desc = "加勒比海域的鱼我们钓的差不多了，把它们放入观赏馆，[color=#ffff00]之后我们将前往全新海域【夏威夷】[/color]！", TaskId = 12, Prev = 11, RewardType = 2, Reward = 60 	},
		{ ID = 13, Name = "累计解锁9个【装饰物】", Desc = "[color=#ffff00]前往【观赏馆】继续升级和解锁更多装饰物吧[/color]，这样就能放入更多的鱼。", TaskId = 13, Prev = 12, RewardType = 2, Reward = 25 	},
		{ ID = 14, Name = "开启【成就】", Desc = "[color=#ffff00]多多钓鱼，多多升级鱼和装饰物，收益提升到【60M/秒】[/color]以上，就可以解锁成就啦！", TaskId = 14, Prev = 13, RewardType = 2, Reward = 25 	},
		{ ID = 15, Name = "获得【钓鱼好手】称号", Desc = "[color=#ffff00]完成更多成就[/color]，不但可提升成就称号，还可以领取成就宝箱哦！", TaskId = 15, Prev = 14, RewardType = 2, Reward = 25 	},
		{ ID = 16, Name = "累计解锁15个【装饰物】", Desc = "[color=#ffff00]前往【观赏馆】[/color]继续升级和解锁更多装饰物吧，这样就能放入更多的鱼。", TaskId = 16, Prev = 15, RewardType = 2, Reward = 60 	},
		{ ID = 17, Name = "【加勒比泡泡珊瑚】升到120级", Desc = "是不是迫不及待的要[color=#ffff00]去【夏威夷钓鱼】[/color]了？稍等，我们很快就出发。", TaskId = 17, Prev = 16, RewardType = 2, Reward = 25 	},
		{ ID = 18, Name = "前往【夏威夷海域】钓鱼", Desc = "谁不喜欢夏威夷呢？[color=#ffff00]进入【钓鱼】，点击右上角【切换海域】[/color]，点击夏威夷海域可查看解锁条件。", TaskId = 18, Prev = 17, RewardType = 2, Reward = 80 	},
		{ ID = 19, Name = "寻找【鬼头刀】", Desc = "[color=#ffff00]在夏威夷海域[/color]【升级】和【挑战】更多鱼类，直至发现鬼头刀并征服它！", TaskId = 19, Prev = 18, RewardType = 2, Reward = 30 	},
		{ ID = 20, Name = "解锁【夏威夷热带风情馆】", Desc = "[color=#ffff00]在【观赏馆】右上角【切换观赏馆】[/color]，可以看到各个观赏馆的解锁条件！", TaskId = 20, Prev = 19, RewardType = 2, Reward = 100 	},
		{ ID = 21, Name = "累计解锁21个【装饰物】", Desc = "[color=#ffff00]前往【夏威夷热带风情馆】[/color]继续升级和解锁更多装饰物吧，这样就能放入更多的鱼。", TaskId = 21, Prev = 20, RewardType = 2, Reward = 35 	},
		{ ID = 22, Name = "寻找【斑点九棘鲈】", Desc = "[color=#ffff00]在夏威夷海域[/color]【升级】和【挑战】更多鱼类，直至发现斑点九棘鲈并征服它！", TaskId = 22, Prev = 21, RewardType = 2, Reward = 80 	},
		{ ID = 23, Name = "累计解锁27个【装饰物】", Desc = "[color=#ffff00]前往【夏威夷热带风情馆】[/color]继续升级和解锁更多装饰物吧，这样就能放入更多的鱼。", TaskId = 23, Prev = 22, RewardType = 2, Reward = 120 	},
		{ ID = 24, Name = "寻找【平鳍旗鱼】并升到130级", Desc = "[color=#ffff00]在夏威夷海域[/color]【升级】和【挑战】更多鱼类，直至发现平鳍旗鱼，征服它之后进行升级", TaskId = 24, Prev = 23, RewardType = 2, Reward = 80 	},
		{ ID = 25, Name = "累计解锁30个【装饰物】", Desc = "[color=#ffff00]前往【夏威夷热带风情馆】[/color]继续升级和解锁更多装饰物吧，这样就能放入更多的鱼。", TaskId = 25, Prev = 24, RewardType = 2, Reward = 80 	},
		{ ID = 26, Name = "【夏威夷日冕海葵】升到300级", Desc = "[color=#ffff00]前往阿拉斯加之前[/color]，我们对夏威夷热带风情馆最后一个装饰物进行一些升级。", TaskId = 26, Prev = 25, RewardType = 2, Reward = 120 	},
		{ ID = 27, Name = "前往【阿拉斯加海域】钓鱼", Desc = "阿拉斯加能看到极光，也是世界唯二的观鲸点，喜欢“海中熊猫”虎鲸吗？[color=#ffff00]点击右上角查看海域解锁条件[/color]。", TaskId = 27, Prev = 26, RewardType = 2, Reward = 80 	},
		{ ID = 28, Name = "寻找【北极茴鱼】", Desc = "[color=#ffff00]在阿拉斯加海域[/color]【升级】和【挑战】更多鱼类，直至发现北极茴鱼并征服它！", TaskId = 28, Prev = 27, RewardType = 2, Reward = 80 	},
		{ ID = 29, Name = "解锁【阿拉斯加冰川极地馆】", Desc = "[color=#ffff00]在【观赏馆】右上角【切换观赏馆】[/color]里可以看到各个观赏馆的解锁条件！", TaskId = 29, Prev = 28, RewardType = 2, Reward = 120 	},
		{ ID = 30, Name = "累计解锁36个【装饰物】", Desc = "[color=#ffff00]前往【阿拉斯加冰川极地馆】[/color]继续升级和解锁更多装饰物吧，这样就能放入更多的鱼。", TaskId = 30, Prev = 29, RewardType = 2, Reward = 80 	},
		{ ID = 31, Name = "获得【钓鱼大师III】称号", Desc = "嗨，据说你已经是个熟练的钓鱼高手，[color=#ffff00]还想更进一步吗[/color]？", TaskId = 31, Prev = 30, RewardType = 2, Reward = 150 	}
	}

}


-- ID
tab.MainTaskByID = {}
for _, rec in pairs(tab.MainTask) do
	tab.MainTaskByID[rec.ID] = rec
end

tab.Enum = {
}

return tab