-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	PlayerDisplay = {
		{ ID = 1, Hp = 1800, NormalDamage = 100, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.72, 0.22, 0.06 }, EventTypes = { 0, 0, 0 }, EventDamages = { 409, 428, 369 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 2, Hp = 2210, NormalDamage = 130, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 505, 507 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 3, Hp = 5330, NormalDamage = 130, DamageHitTime = 0.7, IsHunter = true, EventHpPers = { 0.92, 0.74, 0.61, 0.34, 0.05 }, EventTypes = { 0, 1, 0, 0, 0 }, EventDamages = { 388, 0, 427, 370, 411 }, Xoffset = 0.01193934, Yoffset = 0.0952072, Zoffset = 0.0779113 	},
		{ ID = 4, Hp = 3549, NormalDamage = 169, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 634, 644 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 5, Hp = 3740, NormalDamage = 220, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 891, 934 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 6, Hp = 4862, NormalDamage = 286, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 1195, 1235 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 7, Hp = 9438, NormalDamage = 286, DamageHitTime = 0.7, IsHunter = false, EventHpPers = { 0.91, 0.67, 0.36, 0.06 }, EventTypes = { 0, 0, 0, 0 }, EventDamages = { 789, 785, 791, 930 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 8, Hp = 7812, NormalDamage = 372, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 1451, 1431 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 9, Hp = 8228, NormalDamage = 484, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 1997, 1826 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 10, Hp = 10693, NormalDamage = 629, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 2682, 2718 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 11, Hp = 20757, NormalDamage = 629, DamageHitTime = 0.7, IsHunter = false, EventHpPers = { 0.91, 0.67, 0.36, 0.06 }, EventTypes = { 0, 0, 0, 0 }, EventDamages = { 1839, 1951, 2055, 1892 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 12, Hp = 17178, NormalDamage = 818, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 3502, 3375 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 13, Hp = 18071, NormalDamage = 1063, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 3847, 4458 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 14, Hp = 35079, NormalDamage = 1063, DamageHitTime = 0.7, IsHunter = false, EventHpPers = { 0.91, 0.67, 0.36, 0.06 }, EventTypes = { 0, 0, 0, 0 }, EventDamages = { 3263, 3283, 2906, 2923 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 15, Hp = 29022, NormalDamage = 1382, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 5307, 5747 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 16, Hp = 37737, NormalDamage = 1797, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 6500, 7254 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 17, Hp = 73677, NormalDamage = 1797, DamageHitTime = 0.7, IsHunter = true, EventHpPers = { 0.92, 0.74, 0.61, 0.34, 0.05 }, EventTypes = { 0, 1, 0, 0, 0 }, EventDamages = { 5890, 0, 5895, 4944, 4989 }, Xoffset = 0.01143346, Yoffset = 0.2026406, Zoffset = 0.127055 	},
		{ ID = 18, Hp = 49056, NormalDamage = 2336, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 9297, 9662 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 19, Hp = 51629, NormalDamage = 3037, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 11911, 11491 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 20, Hp = 67116, NormalDamage = 3948, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 16683, 16397 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 21, Hp = 130284, NormalDamage = 3948, DamageHitTime = 0.7, IsHunter = false, EventHpPers = { 0.91, 0.67, 0.36, 0.06 }, EventTypes = { 0, 0, 0, 0 }, EventDamages = { 12305, 11730, 11014, 12124 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 22, Hp = 107772, NormalDamage = 5132, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 21863, 20251 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 23, Hp = 113424, NormalDamage = 6672, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 26250, 24095 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 24, Hp = 147458, NormalDamage = 8674, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.76, 0.12 }, EventTypes = { 0, 0 }, EventDamages = { 31942, 33450 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 25, Hp = 286242, NormalDamage = 8674, DamageHitTime = 0.7, IsHunter = false, EventHpPers = { 0.91, 0.67, 0.36, 0.06 }, EventTypes = { 0, 0, 0, 0 }, EventDamages = { 26743, 24425, 27624, 23565 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 26, Hp = 236796, NormalDamage = 11276, DamageHitTime = 0.9, IsHunter = false, EventHpPers = { 0.71, 0.1 }, EventTypes = { 0, 0 }, EventDamages = { 40749, 42369 }, Xoffset = 0, Yoffset = 0, Zoffset = 0 	},
		{ ID = 27, Hp = 462316, NormalDamage = 11276, DamageHitTime = 0.7, IsHunter = true, EventHpPers = { 0.92, 0.74, 0.61, 0.34, 0.05 }, EventTypes = { 0, 1, 0, 0, 0 }, EventDamages = { 31517, 0, 32016, 35505, 31738 }, Xoffset = 0.01143346, Yoffset = 0.09884061, Zoffset = 0.112955 	}
	}

}


-- ID
tab.PlayerDisplayByID = {}
for _, rec in pairs(tab.PlayerDisplay) do
	tab.PlayerDisplayByID[rec.ID] = rec
end

tab.Enum = {
}

return tab