-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	AchievementTitle = {
		{ ID = 1, Name = "Newbie", Icon = "chengjiu1", Condition = 0, RewardType = 2, Reward = 20 	},
		{ ID = 2, Name = "Rookie", Icon = "chengjiu2", Condition = 10, RewardType = 2, Reward = 50 	},
		{ ID = 3, Name = "Proficient I", Icon = "chengjiu3", Condition = 18, RewardType = 2, Reward = 60 	},
		{ ID = 4, Name = "Proficient II", Icon = "chengjiu3", Condition = 30, RewardType = 2, Reward = 70 	},
		{ ID = 5, Name = "Proficient III", Icon = "chengjiu3", Condition = 40, RewardType = 2, Reward = 80 	},
		{ ID = 6, Name = "Master I", Icon = "chengjiu4", Condition = 50, RewardType = 2, Reward = 90 	},
		{ ID = 7, Name = "Master II", Icon = "chengjiu4", Condition = 60, RewardType = 2, Reward = 100 	},
		{ ID = 8, Name = "Master III", Icon = "chengjiu4", Condition = 75, RewardType = 2, Reward = 110 	},
		{ ID = 9, Name = "Tycoon", Icon = "chengjiu5", Condition = 90, RewardType = 2, Reward = 120 	}
	}, 

	AchievementTask = {
		{ ID = 100001, Name = "Unlock 1 fish in total", TaskId = 100001, Prev = 0, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 100002, Name = "Unlock 3 fish in total", TaskId = 100002, Prev = 100001, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 100003, Name = "Unlock 6 fish in total", TaskId = 100003, Prev = 100002, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 100004, Name = "Unlock 10 fish in total", TaskId = 100004, Prev = 100003, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 100005, Name = "Unlock 15 fish in total", TaskId = 100005, Prev = 100004, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 100006, Name = "Unlock 20 fish in total", TaskId = 100006, Prev = 100005, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 100007, Name = "Unlock 25 fish in total", TaskId = 100007, Prev = 100006, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 200001, Name = "Train 1 time in total", TaskId = 200001, Prev = 0, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200002, Name = "Train 5 times in total", TaskId = 200002, Prev = 200001, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200003, Name = "Train 15 times in total", TaskId = 200003, Prev = 200002, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200004, Name = "Train 30 times in total", TaskId = 200004, Prev = 200003, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200005, Name = "Train 50 times in total", TaskId = 200005, Prev = 200004, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200006, Name = "Train 70 times in total", TaskId = 200006, Prev = 200005, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200007, Name = "Train 100 times in total", TaskId = 200007, Prev = 200006, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200008, Name = "Train 150 times in total", TaskId = 200008, Prev = 200007, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200009, Name = "Train 200 times in total", TaskId = 200009, Prev = 200008, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200010, Name = "Train 250 times in total", TaskId = 200010, Prev = 200009, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200011, Name = "Train 300 times in total", TaskId = 200011, Prev = 200010, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 200012, Name = "Train 360 times in total", TaskId = 200012, Prev = 200011, RewardType = 2, Reward = 5, Ad = 0 	},
		{ ID = 300001, Name = "Unlock 1 decoration in total", TaskId = 300001, Prev = 0, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 300002, Name = "Unlock 5 decorations in total", TaskId = 300002, Prev = 300001, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 300003, Name = "Unlock 10 decorations in total", TaskId = 300003, Prev = 300002, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 300004, Name = "Unlock 15 decorations in total", TaskId = 300004, Prev = 300003, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 300005, Name = "Unlock 20 decorations in total", TaskId = 300005, Prev = 300004, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 300006, Name = "Unlock 25 decorations in total", TaskId = 300006, Prev = 300005, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 300007, Name = "Unlock 30 decorations in total", TaskId = 300007, Prev = 300006, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 300008, Name = "Unlock 35 decorations in total", TaskId = 300008, Prev = 300007, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 300009, Name = "Unlock 40 decorations in total", TaskId = 300009, Prev = 300008, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 300010, Name = "Unlock 45 decorations in total", TaskId = 300010, Prev = 300009, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 400001, Name = "Grow 1 time in total", TaskId = 400001, Prev = 0, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400002, Name = "Grow 5 times in total", TaskId = 400002, Prev = 400001, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400003, Name = "Grow 10 times in total", TaskId = 400003, Prev = 400002, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400004, Name = "Grow 15 times in total", TaskId = 400004, Prev = 400003, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400005, Name = "Grow 20 times in total", TaskId = 400005, Prev = 400004, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400006, Name = "Grow 25 times in total", TaskId = 400006, Prev = 400005, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400007, Name = "Grow 30 times in total", TaskId = 400007, Prev = 400006, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400008, Name = "Grow 35 times in total", TaskId = 400008, Prev = 400007, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400009, Name = "Grow 40 times in total", TaskId = 400009, Prev = 400008, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400010, Name = "Grow 45 times in total", TaskId = 400010, Prev = 400009, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 400011, Name = "Grow 50 times in total", TaskId = 400011, Prev = 400010, RewardType = 2, Reward = 10, Ad = 0 	},
		{ ID = 500001, Name = "Unlock the 2nd fishing area", TaskId = 500001, Prev = 0, RewardType = 2, Reward = 35, Ad = 1 	},
		{ ID = 500002, Name = "Unlock the 3rd fishing area", TaskId = 500002, Prev = 500001, RewardType = 2, Reward = 35, Ad = 1 	},
		{ ID = 600001, Name = "Open 1 Drifting Chest in total", TaskId = 600001, Prev = 0, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600002, Name = "Open 5 Drifting Chests in total", TaskId = 600002, Prev = 600001, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600003, Name = "Open 10 Drifting Chests in total", TaskId = 600003, Prev = 600002, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600004, Name = "Open 15 Drifting Chests in total", TaskId = 600004, Prev = 600003, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600005, Name = "Open 20 Drifting Chests in total", TaskId = 600005, Prev = 600004, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600006, Name = "Open 28 Drifting Chests in total", TaskId = 600006, Prev = 600005, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600007, Name = "Open 36 Drifting Chests in total", TaskId = 600007, Prev = 600006, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600008, Name = "Open 44 Drifting Chests in total", TaskId = 600008, Prev = 600007, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600009, Name = "Open 52 Drifting Chests in total", TaskId = 600009, Prev = 600008, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600010, Name = "Open 60 Drifting Chests in total", TaskId = 600010, Prev = 600009, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600011, Name = "Open 68 Drifting Chests in total", TaskId = 600011, Prev = 600010, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600012, Name = "Open 76 Drifting Chests in total", TaskId = 600012, Prev = 600011, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600013, Name = "Open 84 Drifting Chests in total", TaskId = 600013, Prev = 600012, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600014, Name = "Open 92 Drifting Chests in total", TaskId = 600014, Prev = 600013, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600015, Name = "Open 100 Drifting Chests in total", TaskId = 600015, Prev = 600014, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600016, Name = "Open 110 Drifting Chests in total", TaskId = 600016, Prev = 600015, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600017, Name = "Open 120 Drifting Chests in total", TaskId = 600017, Prev = 600016, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600018, Name = "Open 130 Drifting Chests in total", TaskId = 600018, Prev = 600017, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600019, Name = "Open 140 Drifting Chests in total", TaskId = 600019, Prev = 600018, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600020, Name = "Open 150 Drifting Chests in total", TaskId = 600020, Prev = 600019, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600021, Name = "Open 170 Drifting Chests in total", TaskId = 600021, Prev = 600020, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 600022, Name = "Open 190 Drifting Chests in total", TaskId = 600022, Prev = 600021, RewardType = 2, Reward = 20, Ad = 0 	},
		{ ID = 600023, Name = "Open 210 Drifting Chests in total", TaskId = 600023, Prev = 600022, RewardType = 2, Reward = 20, Ad = 1 	},
		{ ID = 700001, Name = "Watch ad 1 time in total", TaskId = 700001, Prev = 0, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 700002, Name = "Watch ad 5 times in total", TaskId = 700002, Prev = 700001, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 700003, Name = "Watch ad 10 times in total", TaskId = 700003, Prev = 700002, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700004, Name = "Watch ad 15 times in total", TaskId = 700004, Prev = 700003, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 700005, Name = "Watch ad 20 times in total", TaskId = 700005, Prev = 700004, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700006, Name = "Watch ad 25 times in total", TaskId = 700006, Prev = 700005, RewardType = 2, Reward = 15, Ad = 0 	},
		{ ID = 700007, Name = "Watch ad 30 times in total", TaskId = 700007, Prev = 700006, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700008, Name = "Watch ad 40 times in total", TaskId = 700008, Prev = 700007, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700009, Name = "Watch ad 50 times in total", TaskId = 700009, Prev = 700008, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700010, Name = "Watch ad 60 times in total", TaskId = 700010, Prev = 700009, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700011, Name = "Watch ad 70 times in total", TaskId = 700011, Prev = 700010, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700012, Name = "Watch ad 80 times in total", TaskId = 700012, Prev = 700011, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700013, Name = "Watch ad 90 times in total", TaskId = 700013, Prev = 700012, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700014, Name = "Watch ad 100 times in total", TaskId = 700014, Prev = 700013, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700015, Name = "Watch ad 150 times in total", TaskId = 700015, Prev = 700014, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700016, Name = "Watch ad 200 times in total", TaskId = 700016, Prev = 700015, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700017, Name = "Watch ad 250 times in total", TaskId = 700017, Prev = 700016, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700018, Name = "Watch ad 300 times in total", TaskId = 700018, Prev = 700017, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700019, Name = "Watch ad 400 times in total", TaskId = 700019, Prev = 700018, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700020, Name = "Watch ad 500 times in total", TaskId = 700020, Prev = 700019, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700021, Name = "Watch ad 600 times in total", TaskId = 700021, Prev = 700020, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700022, Name = "Watch ad 700 times in total", TaskId = 700022, Prev = 700021, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700023, Name = "Watch ad 800 times in total", TaskId = 700023, Prev = 700022, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700024, Name = "Watch ad 900 times in total", TaskId = 700024, Prev = 700023, RewardType = 2, Reward = 15, Ad = 1 	},
		{ ID = 700025, Name = "Watch ad 1000 times in total", TaskId = 700025, Prev = 700024, RewardType = 2, Reward = 15, Ad = 1 	}
	}

}


-- ID
tab.AchievementTitleByID = {}
for _, rec in pairs(tab.AchievementTitle) do
	tab.AchievementTitleByID[rec.ID] = rec
end

-- ID
tab.AchievementTaskByID = {}
for _, rec in pairs(tab.AchievementTask) do
	tab.AchievementTaskByID[rec.ID] = rec
end

tab.Enum = {
}

return tab