-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	AudioConfig = {
		{ ID = 1, Name = "BGM_Caribbean01", Loops = true, Path = "Audio/BGM_Caribbean01.mp3", Extent = "mp3", Desc = "Caribbean Fishing Scene Music" 	},
		{ ID = 2, Name = "BGM_Hawaii01", Loops = true, Path = "Audio/BGM_Hawaii01.mp3", Extent = "mp3", Desc = "Hawaiian Fishing Scene Music" 	},
		{ ID = 3, Name = "BGM_Alaska01", Loops = true, Path = "Audio/BGM_Alaska01.mp3", Extent = "mp3", Desc = "Alaska Fishing Scene Music" 	},
		{ ID = 40, Name = "BGM_Battle01", Loops = true, Path = "Audio/BGM_Battle01.mp3", Extent = "mp3", Desc = "Stop the scene music after entering the manual fishing scene, and play the battle music after the fish is hooked" 	},
		{ ID = 50, Name = "AMB_SeaWaves01", Loops = true, Path = "Audio/AMB_SeaWaves01.mp3", Extent = "mp3", Desc = "Ocean wave ambient sound" 	},
		{ ID = 55, Name = "AMB_Aquarium", Loops = true, Path = "Audio/AMB_Aquarium.mp3", Extent = "mp3", Desc = "Ambient sound when in the viewing gallery scene" 	},
		{ ID = 60, Name = "AMB_Thunder01", Loops = false, Path = "Audio/AMB_Thunder01.mp3", Extent = "mp3", Desc = "Thunder 1 sound effect" 	},
		{ ID = 61, Name = "AMB_Thunder02", Loops = false, Path = "Audio/AMB_Thunder02.mp3", Extent = "mp3", Desc = "Thunder 2 sound effect" 	},
		{ ID = 100, Name = "Button_Click01", Loops = false, Path = "Audio/Button_Click01.mp3", Extent = "mp3", Desc = "Generic default click sound" 	},
		{ ID = 101, Name = "Button_Click02", Loops = false, Path = "Audio/Button_Click02.mp3", Extent = "mp3", Desc = "Another generic click sound for filling expressiveness" 	},
		{ ID = 102, Name = "Button_ClickCoin01", Loops = false, Path = "Audio/Button_ClickCoin01.mp3", Extent = "mp3", Desc = "General click scene to increase gold coin sound effects" 	},
		{ ID = 103, Name = "Button_Draw", Loops = false, Path = "Audio/Button_Draw.mp3", Extent = "mp3", Desc = "expand button" 	},
		{ ID = 104, Name = "Button_PopUp", Loops = false, Path = "Audio/Button_PopUp.mp3", Extent = "mp3", Desc = "pop-up sound" 	},
		{ ID = 105, Name = "Button_AwardCoin", Loops = false, Path = "Audio/Button_AwardCoin.mp3", Extent = "mp3", Desc = "Generic sound effects for the animation of getting gold coins" 	},
		{ ID = 106, Name = "Button_AwardCoinBanner", Loops = false, Path = "Audio/Button_AwardCoinBanner.mp3", Extent = "mp3", Desc = "Generic gold coin currency bar animation sound effects" 	},
		{ ID = 107, Name = "Button_AwardDiamond", Loops = false, Path = "Audio/Button_AwardDiamond.mp3", Extent = "mp3", Desc = "Universal get diamond animation sound effects" 	},
		{ ID = 108, Name = "Button_AwardDiamondBanner", Loops = false, Path = "Audio/Button_AwardDiamondBanner.mp3", Extent = "mp3", Desc = "Generic diamond currency bar animation sound effects" 	},
		{ ID = 109, Name = "Button_Grid", Loops = false, Path = "Audio/Button_Grid.mp3", Extent = "mp3", Desc = "Progress grid growth sound" 	},
		{ ID = 1000, Name = "Button_Unlock", Loops = false, Path = "Audio/Button_Unlock.mp3", Extent = "mp3", Desc = "Click the [Unlock] button sound effect" 	},
		{ ID = 1001, Name = "Button_Level", Loops = false, Path = "Audio/Button_Level.mp3", Extent = "mp3", Desc = "Click the [Upgrade] button sound effect" 	},
		{ ID = 1002, Name = "Button_Grow", Loops = false, Path = "Audio/Button_Grow.mp3", Extent = "mp3", Desc = "Click the [Growth] button sound effect" 	},
		{ ID = 1003, Name = "Button_PutIn", Loops = false, Path = "Audio/Button_PutIn.mp3", Extent = "mp3", Desc = "Click the [Insert] button sound effect" 	},
		{ ID = 1004, Name = "Button_Bubble", Loops = false, Path = "Audio/Button_Bubble.mp3", Extent = "mp3", Desc = "Click on the fish interactive sound" 	},
		{ ID = 1005, Name = "Button_Evolution", Loops = false, Path = "Audio/Button_Evolution.mp3", Extent = "mp3", Desc = "Fish/decoration evolution sound" 	},
		{ ID = 1006, Name = "Button_CutToBubble", Loops = false, Path = "Audio/Button_CutToBubble.mp3", Extent = "mp3", Desc = "Full screen bubble transition sound effects" 	},
		{ ID = 1007, Name = "Button_BoxClick", Loops = false, Path = "Audio/Button_BoxClick.mp3", Extent = "mp3", Desc = "The sound effect when clicking on the treasure box pop-up window" 	},
		{ ID = 1008, Name = "Button_BoxOpen", Loops = false, Path = "Audio/Button_BoxOpen.mp3", Extent = "mp3", Desc = "The sound when the chest is opened" 	},
		{ ID = 1009, Name = "Button_CutToSea", Loops = false, Path = "Audio/Button_CutToSea.mp3", Extent = "mp3", Desc = "Switch sea area" 	},
		{ ID = 1010, Name = "Button_CutToAquarium", Loops = false, Path = "Audio/Button_CutToAquarium.mp3", Extent = "mp3", Desc = "Toggle viewing gallery" 	},
		{ ID = 3000, Name = "Sfx_CastButton", Loops = false, Path = "Audio/Sfx_CastButton.mp3", Extent = "mp3", Desc = "Sure cast" 	},
		{ ID = 3001, Name = "Sfx_DecideWindow", Loops = false, Path = "Audio/Sfx_DecideWindow.mp3", Extent = "mp3", Desc = "Judgment popup" 	},
		{ ID = 3002, Name = "Sfx_CastWinder", Loops = false, Path = "Audio/Sfx_CastWinder.mp3", Extent = "mp3", Desc = "Reel pay-off sound" 	},
		{ ID = 3003, Name = "Sfx_FallIntoWater", Loops = false, Path = "Audio/Sfx_FallIntoWater.mp3", Extent = "mp3", Desc = "fish hook falls into the water" 	},
		{ ID = 3004, Name = "Sfx_GetHooked", Loops = false, Path = "Audio/Sfx_GetHooked.mp3", Extent = "mp3", Desc = "Fish hook event sound effect" 	},
		{ ID = 3005, Name = "Sfx_Winder01", Loops = true, Path = "Audio/Sfx_Winder01.mp3", Extent = "mp3", Desc = "Press to turn the reel 01" 	},
		{ ID = 3006, Name = "Sfx_Winder02", Loops = true, Path = "Audio/Sfx_Winder02.mp3", Extent = "mp3", Desc = "Press to turn the reel 02" 	},
		{ ID = 3007, Name = "Sfx_LinePull01", Loops = true, Path = "Audio/Sfx_LinePull01.mp3", Extent = "mp3", Desc = "The sound effect of the fishing rod and line being pulled tight (1st gear)" 	},
		{ ID = 3008, Name = "Sfx_LinePull02", Loops = true, Path = "Audio/Sfx_LinePull02.mp3", Extent = "mp3", Desc = "The sound effect of the fishing rod and line being pulled tight (2 files)" 	},
		{ ID = 3009, Name = "Sfx_Slide", Loops = false, Path = "Audio/Sfx_Slide.mp3", Extent = "mp3", Desc = "The swipe operation triggers a successful sound effect" 	},
		{ ID = 3010, Name = "Sfx_SlideHit", Loops = false, Path = "Audio/Sfx_SlideHit.mp3", Extent = "mp3", Desc = "Swipe operation crit drops blood sound" 	},
		{ ID = 3011, Name = "Sfx_FishJump", Loops = false, Path = "Audio/Sfx_FishJump.mp3", Extent = "mp3", Desc = "fish jumping out of water sound effect" 	},
		{ ID = 3012, Name = "Sfx_FishFallIntoWater", Loops = false, Path = "Audio/Sfx_FishFallIntoWater.mp3", Extent = "mp3", Desc = "fish falling into water sound effect" 	},
		{ ID = 3013, Name = "Sfx_FishSurfing", Loops = false, Path = "Audio/Sfx_FishSurfing.mp3", Extent = "mp3", Desc = "The sound effect of the fish being pulled over vigorously" 	},
		{ ID = 3014, Name = "Sfx_FishPullUp", Loops = false, Path = "Audio/Sfx_FishPullUp.mp3", Extent = "mp3", Desc = "Fish out of water sound effect" 	},
		{ ID = 3015, Name = "Sfx_FishStruggle", Loops = false, Path = "Audio/Sfx_FishStruggle.mp3", Extent = "mp3", Desc = "Fish struggling sound effect (with action)" 	}
	}

}


-- ID
tab.AudioConfigByID = {}
for _, rec in pairs(tab.AudioConfig) do
	tab.AudioConfigByID[rec.ID] = rec
end

tab.Enum = {
}

return tab