-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	Functions = {
		{ ID = 1, Title = "Gallery", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 5000, MainTask = 0 	},
		{ ID = 2, Title = "Train", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 2000000, MainTask = 0 	},
		{ ID = 3, Title = "Fishing", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 0 	},
		{ ID = 4, Title = "Yacht", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 8E+16, MainTask = 0 	},
		{ ID = 5, Title = "Achievement", UnlockType = 1, UnlockCost = 0, IncomeSpeed = 50000000, MainTask = 0 	},
		{ ID = 6, Title = "Shipwreck treasure hunt", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 6 	},
		{ ID = 7, Title = "Double income", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 5 	},
		{ ID = 8, Title = "Drifting Chest", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 9 	},
		{ ID = 9, Title = "Pelagic Fishing", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 12 	},
		{ ID = 10, Title = "Meal time", UnlockType = 0, UnlockCost = 0, IncomeSpeed = 0, MainTask = 11 	}
	}

}


-- ID
tab.FunctionsByID = {}
for _, rec in pairs(tab.Functions) do
	tab.FunctionsByID[rec.ID] = rec
end

tab.Enum = {
}

return tab