-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	MainTask = {
		{ ID = 1, Name = "Challenge【Grouper】", Desc = "According to experienced fishermen, this fish often [color=#ffff00]infested in the Caribbean Sea[/color] and southern Florida.", TaskId = 1, Prev = 0, RewardType = 1, Reward = 230000 	},
		{ ID = 2, Name = "Upgrade【Grouper】 to level 10", Desc = "It is said that [color=#ffff00]great white sharks[/color] have appeared in the Caribbean Sea recently, you'd better watch out. Go and challenge more fish!", TaskId = 2, Prev = 1, RewardType = 1, Reward = 690000 	},
		{ ID = 3, Name = "Challenge the 3rd fish", Desc = "It is said that [color=#ffff00]great white sharks[/color] have appeared in the Caribbean Sea recently, so you have to pay attention to safety when you go fishing. Go and challenge more fish!", TaskId = 3, Prev = 2, RewardType = 2, Reward = 50 	},
		{ ID = 4, Name = "Unlock【Gallery】", Desc = "Build a gallery and put all the fish caught in the gallery.", TaskId = 4, Prev = 3, RewardType = 2, Reward = 20 	},
		{ ID = 5, Name = "Unlock【Gallery-Caribbean Bulb Anemone】", Desc = "[color=#ffff00]Unlock the 【Caribbean Bulb Anemone】[/color] in the Gallery, so[color=#ffff00]you can put angelfish in the Gallery[/color]! If the gold coins are not enough, it is recommended to carry out [Shipwreck Treasure Exploration]", TaskId = 5, Prev = 4, RewardType = 2, Reward = 20 	},
		{ ID = 6, Name = "Unlock【Gallery-Caribbean Super Burro’s Tail】", Desc = "[color=#ffff00]Unlock the 【Caribbean Super Burro's Tail】[/color] in the Gallery, so [color=#ffff00] can put grouper in the Gallery[/color]! If the gold coins are not enough, it is recommended to do 【Shipwreck Treasure Hunt】", TaskId = 6, Prev = 5, RewardType = 2, Reward = 20 	},
		{ ID = 7, Name = "Unlock【Caribbean Odd Sea Rocks】", Desc = "We caught a great white, looking forward to putting it in the Gallery? We [color=#ffff00]need to upgrade and unlock more Gallery's 【Decoration】[/color].", TaskId = 7, Prev = 6, RewardType = 2, Reward = 20 	},
		{ ID = 8, Name = "Unlock【Gallery-Caribbean Dofleina Armata】", Desc = "[color=#ffff00]Unlocks enough Decoration[/color] to put in Great White Shark(Juvenile Fish). If the gold coins are not enough, it is recommended to do 【Shipwreck treasure hunt】", TaskId = 8, Prev = 7, RewardType = 2, Reward = 60 	},
		{ ID = 9, Name = "Go to 【Train】", Desc = "Fish more and upgrademore, you can go to the Train [color=#ffff00]after the income increases to 【2M/sec】[/color]!", TaskId = 9, Prev = 8, RewardType = 2, Reward = 20 	},
		{ ID = 10, Name = "【Fishing】Challenge 5 fish in total", Desc = "All the caught fish are in the Gallery now, let's [color=#ffff00] go back to the Caribbean waters to continue 【Fishing】[/color]!", TaskId = 10, Prev = 9, RewardType = 2, Reward = 20 	},
		{ ID = 11, Name = "Find【Purple Amberjack】", Desc = "[color=#ffff00]Continue to upgrade and challenge more fish[/color] until the rare 【Purple Amberjack】is found.", TaskId = 11, Prev = 10, RewardType = 2, Reward = 20 	},
		{ ID = 12, Name = "【Purple Amberjack】Upgrade to level 120", Desc = "We have caught enough fish in the Caribbean Sea, put them in the Gallery. [color=#ffff00]After that, we will go to the new seas 【Hawaii】[/color]!", TaskId = 12, Prev = 11, RewardType = 2, Reward = 60 	},
		{ ID = 13, Name = "Unlock 9 【Decorations】 in total", Desc = "[color=#ffff00]Go to 【Gallery】 to upgrade and unlock more decorations[/color], so that you can put more fish.", TaskId = 13, Prev = 12, RewardType = 2, Reward = 25 	},
		{ ID = 14, Name = "Unlock【Achievement】", Desc = "[color=#ffff00] Fish more and upgrade more, you can unlock Achievement after the income 【60M/sec】[/color]!", TaskId = 14, Prev = 13, RewardType = 2, Reward = 25 	},
		{ ID = 15, Name = "Get 【Proficient】 title", Desc = "[color=#ffff00]Complete more Achievements[/color], you can not only increase the Achievementtitle, but also get the Achievement treasure chest!", TaskId = 15, Prev = 14, RewardType = 2, Reward = 25 	},
		{ ID = 16, Name = "Unlock 15 【Decorations】 in total", Desc = "[color=#ffff00]Go to 【Gallery】[/color] to upgrade and unlock more decorations, so that you can put more fish.", TaskId = 16, Prev = 15, RewardType = 2, Reward = 60 	},
		{ ID = 17, Name = "【Caribbean Bubble Coral】Upgrade to level 120", Desc = "Can't wait to [color=#ffff00]go to 【Hawaii Fishing】[/color]? Hold on, we'll be leaving soon.", TaskId = 17, Prev = 16, RewardType = 2, Reward = 25 	},
		{ ID = 18, Name = "Go fishing in 【Hawaiian Seas】", Desc = "Who doesn't love Hawaii? [color=#ffff00]Enter 【Fishing】, click 【Switch Sea Area】[/color] in the upper right corner, and click the Hawaiian Sea area to view the unlock requirements.", TaskId = 18, Prev = 17, RewardType = 2, Reward = 80 	},
		{ ID = 19, Name = "Find 【Common Dolphinfish】", Desc = "【Upgrade】 and 【Challenge】 more fish in[color=#ffff00]Hawaii[/color] until you discover the Common Dolphinfish and conquer it!", TaskId = 19, Prev = 18, RewardType = 2, Reward = 30 	},
		{ ID = 20, Name = "Unlock 【Hawaii Tropical Style Gallery】", Desc = "[color=#ffff00]In the upper right corner of 【Gallery】[/color], you can see the unlock requirements of each Gallery!", TaskId = 20, Prev = 19, RewardType = 2, Reward = 100 	},
		{ ID = 21, Name = "Unlock 21 【Decorations】 in total", Desc = "[color=#ffff00]Go to the 【Hawaii Tropical Style Gallery】[/color] Continue to upgrade and unlock more decorations, so that you can put more fish.", TaskId = 21, Prev = 20, RewardType = 2, Reward = 35 	},
		{ ID = 22, Name = "Find【Cephalopholis Argus】", Desc = "【Upgrade】 and 【Challenge】 more fish in[color=#ffff00]Hawaii[/color] until you discover the Cephalopholis Argus and conquer it!", TaskId = 22, Prev = 21, RewardType = 2, Reward = 80 	},
		{ ID = 23, Name = "Unlock 27 【Decorations】 in total", Desc = "[color=#ffff00]Go to the 【Hawaii Tropical Style Gallery】[/color] Continue to upgrade and unlock more decorations, so that you can put more fish.", TaskId = 23, Prev = 22, RewardType = 2, Reward = 120 	},
		{ ID = 24, Name = "Find 【Indo-Pacific Sailfish】and reach level 130", Desc = "【Upgrade】 and 【Challenge】 more fish in[color=#ffff00]Hawaii[/color] until you discover the Cephalopholis Argus, conquer it and then upgrade", TaskId = 24, Prev = 23, RewardType = 2, Reward = 80 	},
		{ ID = 25, Name = "Unlock 30 【Decorations】 in total", Desc = "[color=#ffff00]Go to the 【Hawaii Tropical Style Gallery】[/color] Continue to upgrade and unlock more decorations, so that you can put more fish.", TaskId = 25, Prev = 24, RewardType = 2, Reward = 80 	},
		{ ID = 26, Name = "【Hawaiian Corona Anemone】Upgrade to level 300", Desc = "[color=#ffff00]Before heading to Alaska[/color], let_x0001_s make some upgrades to the last decoration of the Hawaii Tropical Gallery.", TaskId = 26, Prev = 25, RewardType = 2, Reward = 120 	},
		{ ID = 27, Name = "Go fishing in 【Alaska Seas】", Desc = "Alaska can see the aurora and is the only whale watching spot in the world. Do you like the \"Panda in the Sea\" Killer Whale? [color=#ffff00]Click the upper right corner to view the sea area unlock requirements[/color].", TaskId = 27, Prev = 26, RewardType = 2, Reward = 80 	},
		{ ID = 28, Name = "Find【Arctic Grayling】", Desc = "【Upgrade】 and 【Challenge】 more fish in[color=#ffff00]Alaska[/color] until you discover the Arctic Grayling and conquer it!", TaskId = 28, Prev = 27, RewardType = 2, Reward = 80 	},
		{ ID = 29, Name = "Unlock 【Alaska Glacier Polar Gallery】", Desc = "[color=#ffff00]In the upper right corner of 【Gallery】[/color], you can see the unlock requirements of each Gallery!", TaskId = 29, Prev = 28, RewardType = 2, Reward = 120 	},
		{ ID = 30, Name = "Unlock 36 【Decorations】in total", Desc = "[color=#ffff00]Go to the 【Alaska Glacier Polar Gallery】[/color] Continue to upgrade and unlock more decorations, so that you can put more fish.", TaskId = 30, Prev = 29, RewardType = 2, Reward = 80 	},
		{ ID = 31, Name = "Get 【Fishing Master III】 title", Desc = "Hi, it is said that you are already a proficient fisherman. [color=#ffff00]Do you want to be better[/color]?", TaskId = 31, Prev = 30, RewardType = 2, Reward = 150 	}
	}

}


-- ID
tab.MainTaskByID = {}
for _, rec in pairs(tab.MainTask) do
	tab.MainTaskByID[rec.ID] = rec
end

tab.Enum = {
}

return tab