-- Generated by github.com/davyxu/tabtoy
-- Version: 3.0.1

local tab = {
	Seas = {
		{ ID = 3000001, Name = "Caribbean Seas", Desc = "Bahamas Beach", Audio = 1, Icon = "MainCity/小地图", Scene = "Assets/Scenes/FishingSeas/Caribbean_Fishing.unity", Products = { 1001001, 1001002, 1001003, 1001004, 1001005, 1001006, 1001007 }, Depends = 0 	},
		{ ID = 3000002, Name = "Hawaiian Seas", Desc = "Tropical", Audio = 2, Icon = "MainCity/小地图", Scene = "Assets/Scenes/FishingSeas/Hawaii_Fishing.unity", Products = { 1002001, 1002002, 1002003, 1002004, 1002005, 1002006, 1002007, 1002008, 1002009, 1002010 }, Depends = 1002001 	},
		{ ID = 3000003, Name = "Alaska Seas", Desc = "Aurora Glacier", Audio = 3, Icon = "MainCity/小地图", Scene = "Assets/Scenes/FishingSeas/Alaska_Fishing.unity", Products = { 1003001, 1003002, 1003003, 1003004, 1003005, 1003006, 1003007, 1003008, 1003009, 1003010 }, Depends = 1003001 	}
	}, 

	Products = {
		{ ID = 1001001, Type = 1, ItemID = 1001001, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1001002, Type = 1, ItemID = 1001002, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1001003, Type = 1, ItemID = 1001003, CostTime = 0, ADUnlock = false, Reward = 20, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1001004, Type = 1, ItemID = 1001004, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1001005, Type = 1, ItemID = 1001005, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1001006, Type = 1, ItemID = 1001006, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1001007, Type = 1, ItemID = 1001007, CostTime = 0, ADUnlock = false, Reward = 240, RewardType = 3, EnableAD = true, RewardAD = 3 	},
		{ ID = 1002001, Type = 1, ItemID = 1002001, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1002002, Type = 1, ItemID = 1002002, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1002003, Type = 1, ItemID = 1002003, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1002004, Type = 1, ItemID = 1002004, CostTime = 0, ADUnlock = false, Reward = 240, RewardType = 3, EnableAD = true, RewardAD = 3 	},
		{ ID = 1002005, Type = 1, ItemID = 1002005, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1002006, Type = 1, ItemID = 1002006, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1002007, Type = 1, ItemID = 1002007, CostTime = 0, ADUnlock = false, Reward = 240, RewardType = 3, EnableAD = true, RewardAD = 3 	},
		{ ID = 1002008, Type = 1, ItemID = 1002008, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1002009, Type = 1, ItemID = 1002009, CostTime = 0, ADUnlock = false, Reward = 5, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1002010, Type = 1, ItemID = 1002010, CostTime = 0, ADUnlock = false, Reward = 240, RewardType = 3, EnableAD = true, RewardAD = 3 	},
		{ ID = 1003001, Type = 1, ItemID = 1003001, CostTime = 0, ADUnlock = false, Reward = 10, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1003002, Type = 1, ItemID = 1003002, CostTime = 0, ADUnlock = false, Reward = 10, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1003003, Type = 1, ItemID = 1003003, CostTime = 0, ADUnlock = false, Reward = 10, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1003004, Type = 1, ItemID = 1003004, CostTime = 0, ADUnlock = false, Reward = 240, RewardType = 3, EnableAD = true, RewardAD = 3 	},
		{ ID = 1003005, Type = 1, ItemID = 1003005, CostTime = 0, ADUnlock = false, Reward = 10, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1003006, Type = 1, ItemID = 1003006, CostTime = 0, ADUnlock = false, Reward = 10, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1003007, Type = 1, ItemID = 1003007, CostTime = 0, ADUnlock = false, Reward = 10, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1003008, Type = 1, ItemID = 1003008, CostTime = 0, ADUnlock = false, Reward = 240, RewardType = 3, EnableAD = true, RewardAD = 3 	},
		{ ID = 1003009, Type = 1, ItemID = 1003009, CostTime = 0, ADUnlock = false, Reward = 10, RewardType = 2, EnableAD = false, RewardAD = 3 	},
		{ ID = 1003010, Type = 1, ItemID = 1003010, CostTime = 0, ADUnlock = false, Reward = 240, RewardType = 3, EnableAD = true, RewardAD = 3 	}
	}

}


-- ID
tab.SeasByID = {}
for _, rec in pairs(tab.Seas) do
	tab.SeasByID[rec.ID] = rec
end

-- ID
tab.ProductsByID = {}
for _, rec in pairs(tab.Products) do
	tab.ProductsByID[rec.ID] = rec
end

tab.Enum = {
}

return tab